name: SlashSpec
description: |
  Allow players to temporarily fly around in spectator mode.
  Useful for SMP servers.

author: SeriousGuy888 (billzonium trioxide)
website: https://github.com/SeriousGuy888/SlashSpec

version: "1.0"
main: io.github.seriousguy888.slashspec.SlashSpec
api-version: 1.20
load: POSTWORLD

softdepend:
  - ProtocolLib

commands:
  spec:
    description: Temporarily enter spectator mode to fly around. Run again to go back to survival.
    permission: slashspec.use
    aliases:
      - s
      - sp

# Register permissions here so that LuckPerms can autocomplete properly, since it wasn't detecting some of
# the permissions correctly for some reason.
permissions:
  slashspec.use_hotbar_teleport_menu:
    default: op
    description: |
      Restores normal usage of the teleport menu that replaces the hotbar in spectator mode.
      Disabled by default for normal players so they cannot teleport to people while using /spec.
  slashspec.use:
    default: true
    description: Allows access to the main /spec command's functionality - toggling spectator mode.
  slashspec.firework:
    default: op
  slashspec.force:
    default: op
  slashspec.ghost:
    default: op